add connect-lwM2M.md
Edgenesis/shifu.dev pull request #324
Opened 2024-10-29 03:34 UTC by beingStrongeryqqq

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
add a lwm2m case
#### Which issue(s) this PR fixes:

Fixes #

#### How is this PR tested:
- [ ] unit test
- [ ] e2e test
- [x] other (please specify)

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-10-30 10:35 UTC, tomqin93 requested changes
@beingStrongeryqqq added some comments, please take a look

2024-10-30 10:35 UTC, tomqin93 commented on docs/guides/cases/connect-lwM2M.md
> +title: Connect a lwM2M Device
`LwM2M`, same for other occurrences.

2024-10-30 10:35 UTC, tomqin93 commented on docs/guides/cases/connect-lwM2M.md
> +:::note OPC UA Introduction
LwM2M Introduction

2024-10-30 10:35 UTC, tomqin93 commented on docs/guides/cases/connect-lwM2M.md
> +## Start Shifu's lwM2M Components
This should be a guide on how to use LwM2M deviceShifu from our repo to connect a real LwM2M device, not just running the example itself

2025-01-02 07:01 UTC, kris21he commented
duplicate with https://github.com/Edgenesis/shifu.dev/pull/335

2025-01-02 07:01 UTC, closed without merging