add gateway api reference
Edgenesis/shifu.dev pull request #327
Opened 2024-10-29 06:52 UTC by beingStrongeryqqq

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
add gateway api reference
#### Which issue(s) this PR fixes:

Fixes #

#### How is this PR tested:
- [ ] unit test
- [ ] e2e test
- [x] other (please specify)

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-10-30 10:45 UTC, tomqin93 requested changes
@beingStrongeryqqq added some comments, need to refactor the document for gateway related document

2024-10-30 10:45 UTC, tomqin93 commented on docs/references/api/deviceshifu-configmap.md
> +        gatewayPropertyList:
this should be a separate section since it is gateway property not protocol property

2024-10-30 10:45 UTC, tomqin93 commented on docs/references/api/deviceshifu-configmap.md
> +
does Gateway has telemetry?

2024-10-30 10:45 UTC, tomqin93 commented on docs/references/api/deviceshifu-deployment.md
> +- **spec.template.metadata.labels.app** (string)<br/>label for identifying the thermometer gateway application, specified as `deviceshifu-thermometer-deployment`.
need to revise this section

2025-01-02 07:02 UTC, kris21he commented
duplicate with https://github.com/Edgenesis/shifu.dev/pull/338

2025-01-02 07:02 UTC, closed without merging